export const type={ 
    SHOW_PROGRESS:"SHOW_PROGRESS",
    HIDE_PROGRESS:"HIDE_PROGRESS",
    TOGGLE_PROGRESS:"TOGGLE_PROGRESS",
    SET_STATES:"SET_STATES",
    SET_DISTRICTS:"SET_DISTRICTS",
    SET_VACCINE:"SET_VACCINE",
    SET_VACCINE_COPY:"SET_VACCINE_COPY",
    SET_USERDATA:"SET_USERDATA",
    SELECT_STATE:"SELECT_STATE",
    SELECT_DISTRICT:"SELECT_DISTRICT",
    SELECT_PINCODE:"SELECT_PINCODE",
    TOGGLE_LABEL:"TOGGLE_LABEL",
    TOGGLE_LNDNG_PAGE_TAB:"TOGGLE_LNDNG_PAGE_TAB",
    TOGGLE_VACCINE_PAGE_TAB:"TOGGLE_VACCINE_PAGE_TAB",
    TOGGLE_LOGOUT_POPUP:"TOGGLE_LOGOUT_POPUP",
    SET_VACCINE_FILTERS:"SET_VACCINE_FILTERS"
};